title: "Oat Bot"
description: "Web development made Tasty."
url: http://oatbot.com
baseurl: # apply repo name if use it under gh-pages branch

# Build settings
permalink   : /:year/:title/
markdown    : kramdown
highlighter : rouge

source: ./
destination: ./_site

# Sass configuration
sass:
  sass_dir: assets/scss
  style: compressed # expanded

# Author settings
author:
  name     : "Oat Bot"
  job      : "<strong>makes apps & websites</strong> <em>for you</em>"
  bio      : "I've made many great things; recently, I re-designed the online-store for a top London Raw Food Restaurant, and currently re-combob-ulizing the new website for the city's finest Graphic Novel Publisher."
  thumb    : /images/author.jpg
  github   : http://github.com/oat-bot
  twitter  : http://twitter.com/dino_k_29

gems:
  - bourbon
  - jekyll-paginate

exclude: ["gulp", "node_modules", "bower", "bower_components", "config.rb", "src", "Gemfile", "Gemfile.lock", ".rvmrc", ".rbenv-version", "package.json", "gulpfile.js", "README.md", "Rakefile", "changelog.md"]
